//
//     Generated by class-dump 3.5 (64 bit) (forked by @manicmaniac) (Debug version compiled Jun  9 2022 00:51:00).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <VisualTestKit/VTKStoreManagerSaveResult-Protocol.h>

@class NSString, NSURL;

__attribute__((visibility("hidden")))
@interface VTKFileStoreManagerResult : NSObject <VTKStoreManagerSaveResult>
{
    NSURL *_rootFolderItemsURL;
}

@property(readonly, nonatomic) NSURL *rootFolderItemsURL; // @synthesize rootFolderItemsURL=_rootFolderItemsURL;
@property(readonly, nonatomic) NSString *saveDescription;
- (id)initWithURL:(id)arg1;


@end

