//
//     Generated by class-dump 3.5 (64 bit) (forked by @manicmaniac) (Debug version compiled Jun  9 2022 00:51:00).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <VisualTestKit/VTKReferenceItemsSource-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface VTKFileReferenceItemsSource : NSObject <VTKReferenceItemsSource>
{
    NSString *_itemsDirectory;
}

@property(copy, nonatomic) NSString *itemsDirectory; // @synthesize itemsDirectory=_itemsDirectory;
- (id)referenceImageWithID:(id)arg1 testCase:(id)arg2 error:(id *)arg3;


@end

