//
//     Generated by class-dump 3.5 (64 bit) (forked by @manicmaniac) (Debug version compiled Jun  9 2022 00:51:00).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <VisualTestKit/VTKDrawItem-Protocol.h>

@class NSString, UIColor;

__attribute__((visibility("hidden")))
@interface VTKSquareDrawItem : NSObject <VTKDrawItem>
{
    UIColor *_color;
    struct CGRect _frame;
}

@property(readonly, nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(readonly, nonatomic) UIColor *color; // @synthesize color=_color;
- (void)drawAtContext:(id)arg1;
- (id)initWitColor:(id)arg1 frame:(struct CGRect)arg2;


@end

