//
//     Generated by class-dump 3.5 (64 bit) (forked by @manicmaniac) (Debug version compiled Jun  9 2022 00:51:00).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (VTKSnapshot)
- (id)vtk_SnapshotWithScale:(double)arg1;
- (id)vtk_Snapshot;
@end

