//
//     Generated by class-dump 3.5 (64 bit) (forked by @manicmaniac) (Debug version compiled Jun  9 2022 00:51:00).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@protocol VTKAssertID <NSObject>
@property(readonly, nonatomic) unsigned long long vtkIDDecorationsMask;
@property(readonly, nonatomic) NSString *vtkAssertName;
@end

