//
//     Generated by class-dump 3.5 (64 bit) (forked by @manicmaniac) (Debug version compiled Jun  9 2022 00:51:00).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <VisualTestKit/VTKStoreManager-Protocol.h>

@class NSString, VTKFileStoreManager;

__attribute__((visibility("hidden")))
@interface VTKAttachmentStoreManager : NSObject <VTKStoreManager>
{
    VTKFileStoreManager *_fileStoreManager;
}

@property(readonly, nonatomic) VTKFileStoreManager *fileStoreManager; // @synthesize fileStoreManager=_fileStoreManager;
@property(copy, nonatomic) NSString *itemsDirectory;
- (id)saveItems:(id)arg1 withID:(id)arg2 testCase:(id)arg3;
- (id)init;


@end

