//
//     Generated by class-dump 3.5 (64 bit) (forked by @manicmaniac) (Debug version compiled Jun  9 2022 00:51:00).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol VTKColor;

@protocol VTKColorDifferenceStrategy <NSObject>
@property(readonly, nonatomic) double tolerance;
- (double)differenceBetweenColor:(id <VTKColor>)arg1 andColor:(id <VTKColor>)arg2;

@optional
- (double)antiAliasingDifferenceBetweenColor:(id <VTKColor>)arg1 andColor:(id <VTKColor>)arg2;
@end

