//
//     Generated by class-dump 3.5 (64 bit) (forked by @manicmaniac) (Debug version compiled Jun  9 2022 00:51:00).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol VTKColor
@property(readonly, nonatomic) double alpha;
@property(readonly, nonatomic) double blue;
@property(readonly, nonatomic) double green;
@property(readonly, nonatomic) double red;
@end

