//
//     Generated by class-dump 3.5 (64 bit) (forked by @manicmaniac) (Debug version compiled Jun  9 2022 00:51:00).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UIImage, VTKCompareResult;

@protocol VTKComparator <NSObject>
- (VTKCompareResult *)compareImage:(UIImage *)arg1 withImage:(UIImage *)arg2;
@end

