//
//     Generated by class-dump 3.5 (64 bit) (forked by @manicmaniac) (Debug version compiled Jun  9 2022 00:51:00).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <VisualTestKit/NSObject-Protocol.h>

@class NSString, UIImage, XCTestCase;
@protocol VTKAssertID;

@protocol VTKReferenceItemsSource <NSObject>
- (UIImage *)referenceImageWithID:(id <VTKAssertID>)arg1 testCase:(XCTestCase *)arg2 error:(id *)arg3;

@optional
@property(copy, nonatomic) NSString *itemsDirectory;
@end

