//
//     Generated by class-dump 3.5 (64 bit) (forked by @manicmaniac) (Debug version compiled Jun  9 2022 00:51:00).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSData, NSString;
@protocol VTKAssertID;

@protocol VTKStoreManagerItem <NSObject>
@property(readonly, nonatomic) NSData *itemData;
- (NSString *)fileNameWithTestID:(id <VTKAssertID>)arg1;
@end

