//
//     Generated by class-dump 3.5 (64 bit) (forked by @manicmaniac) (Debug version compiled Jun  9 2022 00:51:00).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <VisualTestKit/VTKStoreManagerItem-Protocol.h>
#import <VisualTestKit/VTKTestAttachment-Protocol.h>

@class NSData, NSString;

__attribute__((visibility("hidden")))
@interface VTKStoreManagerItem : NSObject <VTKStoreManagerItem, VTKTestAttachment>
{
    NSData *_itemData;
    unsigned long long _itemType;
    NSString *_fileExtension;
}

+ (id)itemWithView:(id)arg1;
@property(readonly, nonatomic) NSString *fileExtension; // @synthesize fileExtension=_fileExtension;
@property(readonly, nonatomic) unsigned long long itemType; // @synthesize itemType=_itemType;
@property(readonly, nonatomic) NSData *itemData; // @synthesize itemData=_itemData;
- (id)attachWithThestID:(id)arg1;
- (id)fileNameWithTestID:(id)arg1;
- (id)initWithData:(id)arg1 itemType:(unsigned long long)arg2;


@end

