//
//     Generated by class-dump 3.5 (64 bit) (forked by @manicmaniac) (Debug version compiled Jun  9 2022 00:51:00).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCTest/XCTestCase.h>

@class VTKAssert, VTKInternalConfiguration;

@interface XCTestCase (VisualTestKit)
@property(retain, nonatomic) VTKInternalConfiguration *VisualTestKitConfiguration;
@property(readonly, nonatomic) VTKAssert *VisualTestKitAssert;
@end

