name: Build

on:
  push:
    branches: [ main, fix-ci ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: zsh --login --errexit --pipefail {0}

jobs:
  build-package:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - name: Swift Tools Version
        run: swift package tools-version
      - name: Describe Package
        run: swift package describe
      - name: Build Package
        run: xcodebuild -scheme VisualTestKit -destination "platform=iOS Simulator,name=iPhone 12 Pro"
