name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - experiment/create-release/**
    tags: 'v*' # Semantic Version tag

defaults:
  run:
    shell: zsh --login --errexit --pipefail {0}

jobs:
  create-release:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - name: Zip Xcode Framework
        run: |
          zip -r VisualTestKit.xcframework.zip VisualTestKit.xcframework
          shasum -a 256 VisualTestKit.xcframework.zip
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: true
          prerelease: true
          fail_on_unmatched_files: true
          body: |
            Automatically Created Release
          files: VisualTestKit.xcframework.zip
