name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - experiment/create-release/**
    tags: 'v*' # Semantic Version tag 

jobs:
  create-release:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - name: Compress Xcode Framework
        run: zip VisualTestKit.xcframework.zip "./VisualTestKit.xcframework/**/*"
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: true
          prerelease: true
          fail_on_unmatched_files: true
          body: |
            Automatically Created Release
          files: VisualTestKit.xcframework.zip
